version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/orb-tools
  orb-tools: circleci/orb-tools@10.0
  # https://circleci.com/developer/orbs/orb/circleci/bats
  bats: circleci/bats@1.0
  # https://circleci.com/developer/orbs/orb/circleci/shellcheck
  shellcheck: circleci/shellcheck@2.0
  # https://circleci.com/developer/orbs/orb/circleci/circleci-cli
  cli: circleci/circleci-cli@0.1

parameters:
  packed_orb_path:
    description: >
      The local path where the packed orb will be created by this pipeline
    type: string
    default: _build_/orb.yml

jobs:
  publish:
    description: Uses the CLI to publish the orb to a registry.
    executor: cli/default
    parameters:
      from:
        description: >
          The local path where the packed orb can be found
        type: string
      to:
        description: >
          The orb registry (in the format <namespace>/<orb-name>) where the
          build is going to be published.
        type: string
    steps:
      - run:
          command: |
            circleci orb publish --skip-update-check \
            << parameters.from >> << parameters.to >>@0.1.0+${CIRCLE_SHA1:0:7}.${CIRCLE_BUILD_NUM}
          name: |
            Publish orb at << parameters.from >> to << parameters.to >>

workflows:
  orb-pipeline:
    jobs:
      - orb-tools/lint:
          name: lint-yaml-files

      - orb-tools/pack:
          name: pack-orb-source
          destination-orb-path: << pipeline.parameters.packed_orb_path >>

      - shellcheck/check:
          name:    check-shell-scripts-syntax
          dir:     ./src/scripts
          exclude: SC2148

      # https://github.com/sstephenson/bats
      - bats/run:
          name: run-bats-tests
          path: ./src/tests

      - publish:
          name: publish-to-dev-repo
          from: << pipeline.parameters.packed_orb_path >>
          to:   relaxdiego/service-pipeline-dev
          requires:
            - lint-yaml-files
            - pack-orb-source
            - check-shell-scripts-syntax
            - run-bats-tests
          filters:
            branches:
              only:
                - main
                - release/.*
            tags:
              ignore:
                - .*

      # - integration-test:
      #     requires:
      #       - publish-to-dev-repo
      #
      # - publish:
      #     name: promote-to-qa-repo
      #     to:   relaxdiego/service-pipeline-qa
      #     requires:
      #       - integration-test
      #
      # - approve-promotion-to-production:
      #     type: approval
      #     requires:
      #       - promote-to-qa-repo
      #
      # - publish:
      #     name: promote-to-production-repo
      #     to:   relaxdiego/service-pipeline
      #     requires:
      #       - approve-promotion-to-production
