version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/relaxdiego/service-pipeline
  service-pipeline: relaxdiego/service-pipeline@<<pipeline.parameters.dev-orb-version>>
  # https://circleci.com/developer/orbs/orb/circleci/orb-tools
  orb-tools: circleci/orb-tools@10.0
  # https://circleci.com/developer/orbs/orb/circleci/bats
  bats: circleci/bats@1.0
  # https://circleci.com/developer/orbs/orb/circleci/shellcheck
  shellcheck: circleci/shellcheck@2.0

#
# Pipeline Parameters
#
# IMPORTANT: These parameters are used internally by orb-tools. Skip to
#            the Jobs section.
#
parameters:
  run-integration-tests:
    description: >
      An internal flag to prevent integration test from running before a
      development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test. This value is automatically
      adjusted by the "trigger-integration-tests-workflow" job to correspond
      with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  # Jobs that utilize this orb's commands and parameters to validate changes.
  integration-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # "greet" is a sample command packaged with this orb config.
      # This sample integration test will run as long as the greet command
      # exists. Once you remove the greet command you should remove this line.
      # Push new changes first, before adding new tests to your config.
      - service-pipeline/greet

workflows:
  package-pipeline:
    jobs:
      - orb-tools/lint:
          name: lint-yaml-files

      - orb-tools/pack:
          name: pack-orb-source

      - shellcheck/check:
          name:    check-shell-scripts-syntax
          dir:     ./src/scripts
          exclude: SC2148

      # https://github.com/sstephenson/bats
      - bats/run:
          name: run-bats-tests
          path: ./src/tests
      #
      # - publish:
      #     name: publish-to-dev-repo
      #     to:   relaxdiego/service-pipeline-dev
      #     requires:
      #       - orb-tools/lint
      #       - orb-tools/pack
      #       - bats/run
      #       - shellcheck/check
      #
      # - integration-test:
      #     requires:
      #       - publish-to-dev-repo
      #
      # - publish:
      #     name: promote-to-qa-repo
      #     to:   relaxdiego/service-pipeline-qa
      #     requires:
      #       - integration-test
      #
      # - approve-promotion-to-production:
      #     type: approval
      #     requires:
      #       - promote-to-qa-repo
      #
      # - publish:
      #     name: promote-to-production-repo
      #     to:   relaxdiego/service-pipeline
      #     requires:
      #       - approve-promotion-to-production
